Config:
	username: '*****'
	password: '**********'
	homePage: 'https://kktix.com/'
	ticketPage: 'https://kktix.com/events/jolin0421-2/registrations/new'
	executable_path: '/Users/tyyen/Downloads/chromedriver'
	ticketCount: 2